Updated Makefile

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -31,7 +31,7 @@ jobs:
       run: docker start enimax-build
 
     - name: Cloning the repo
-      run: echo $BRANCH && docker exec enimax-build sh -c "(rm enimax -rf || echo 'Could not delete the folder') && git clone https://github.com/enimax-anime/enimax && cd enimax && git checkout $BRANCH"
+      run: docker exec enimax-build sh -c "(rm enimax -rf || echo 'Could not delete the folder') && git clone https://github.com/enimax-anime/enimax && cd enimax && git checkout $BRANCH"
       env: 
         BRANCH:  ${{steps.branch-name.outputs.current_branch}}
 
@@ -41,7 +41,7 @@ jobs:
         docker cp ./key.jks enimax-build:/usr/src/key.jks
 
     - name: Building the app
-      run:  docker exec enimax-build sh -c "cd enimax && cat build.json && make cordova && make build"
+      run:  docker exec enimax-build sh -c "cd enimax && make cordova && make build"
 
     - name: Fetching the built APK
       run: docker cp enimax-build:/usr/src/enimax/platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk ./      
