Updated main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -31,7 +31,7 @@ jobs:
       run: docker start enimax-build
 
     - name: Cloning the repo
-      run: echo $BRANCH && docker exec enimax-build sh -c "(rm enimax -rf || echo 'Could not delete the folder') && git clone https://github.com/enimax-anime/enimax"
+      run: echo $BRANCH && docker exec enimax-build sh -c "(rm enimax -rf || echo 'Could not delete the folder') && git clone https://github.com/enimax-anime/enimax && cd enimax && git checkout docker"
       env: 
         BRANCH:  ${{steps.branch-name.outputs.default_branch}}
 
